# NumPy  

* by Code with Harry
>YouTube video link: https://www.youtube.com/watch?v=Rbh1rieb3zc

### Why Numpy?
* Numpy provides efficient storage
  * uses relatively less memory to store data
* It's fast
* Unlike lists **randomly accessible**  


In [1]:
import numpy as np

In [ ]:
myarr = np.array([[3,6,3266646, 7]], np.int32)

In [ ]:
myarr[0,1]

6

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr.dtype

dtype('int32')

In [ ]:
myarr

array([[      3,       6, 3266646,       7]], dtype=int32)

### Array creation: Conversion from other Python structures

In [ ]:
listarray = np.array([[1,2,3], [5,8,5], [8,0,3]])

In [ ]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [8, 0, 3]])

In [ ]:

listarray.dtype

dtype('int64')

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.size

9

In [ ]:
np.array({34,21,23})
# objects not efficient for calculations

array({34, 21, 23}, dtype=object)

In [ ]:
# 
zeros = np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

dtype('float64')

In [ ]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace = np.linspace(0,36,5)
lspace

array([ 0.,  9., 18., 27., 36.])

In [ ]:
emp = np.empty((4,3))
emp

array([[4.68298782e-310, 4.68298760e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.36598737e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
emp_like = np.empty_like(lspace)
emp_like

array([ 0.,  9., 18., 27., 36.])

In [ ]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr = arr.reshape(3, 33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(99,)

### NUMPY AXIS
> Number of axis required to represent the array

for a 2D array x is axis0 and y is axis1

In [ ]:
x = listarray

In [ ]:
x

array([[1, 2, 3],
       [5, 8, 5],
       [8, 0, 3]])

In [ ]:
x[0][0] =0

In [ ]:
x

array([[0, 2, 3],
       [5, 8, 5],
       [8, 0, 3]])

In [ ]:
listarray
# x points to listarray

array([[0, 2, 3],
       [5, 8, 5],
       [8, 0, 3]])

In [ ]:
x.sum(axis=0)

array([13, 10, 11])

In [ ]:
x.sum(axis=1)

array([ 5, 18, 11])

In [ ]:
x.T
# transpose

array([[0, 5, 8],
       [2, 8, 0],
       [3, 5, 3]])

In [ ]:
x.flat
# gives an iterator

In [ ]:
for item in x.flat:
  print(item)

0
2
3
5
8
5
8
0
3


In [ ]:
x.ndim
# number of dimension

2

In [ ]:
x.size
# no. of elements

9

In [ ]:
x.nbytes
# total bytes consumed

72

In [ ]:
one = np.array([1,3,51,43])

In [ ]:
one.argmax()
# index of max element

2

In [ ]:
one.argmin()

0

In [ ]:
one.argsort()
# indices in sorted array

array([0, 1, 3, 2])

In [ ]:
x.argmax()

4

In [ ]:
x.argsort()

array([[0, 1, 2],
       [0, 2, 1],
       [1, 2, 0]])

In [ ]:
x

array([[0, 2, 3],
       [5, 8, 5],
       [8, 0, 3]])

In [ ]:
x.argmax(axis=0)

array([2, 1, 1])

In [ ]:
x.argmax(axis=1)

array([2, 1, 0])

In [ ]:
y = x.T
y

array([[0, 5, 8],
       [2, 8, 0],
       [3, 5, 3]])

### Mathematical Operations

In [ ]:
x + y

array([[ 0,  7, 11],
       [ 7, 16,  5],
       [11,  5,  6]])

In [ ]:
x*y
# element wise multiplecation

array([[ 0, 10, 24],
       [10, 64,  0],
       [24,  0,  9]])

In [ ]:
np.sqrt(x)
# element wise sqrt

array([[0.        , 1.41421356, 1.73205081],
       [2.23606798, 2.82842712, 2.23606798],
       [2.82842712, 0.        , 1.73205081]])

In [ ]:
x.sum()

34

In [ ]:
x.max()

8

In [ ]:
np.where(x>5)

(array([1, 2]), array([1, 0]))

In [ ]:
type(np.where(x>5))

tuple

In [ ]:
np.count_nonzero(x)

7

In [ ]:
np.nonzero(x)

(array([0, 0, 1, 1, 1, 2, 2]), array([1, 2, 0, 1, 2, 0, 2]))

### Numpy storage comparision

In [ ]:
import sys

list_ar = [0,45, 5, 5]

In [ ]:
np_ar = np.array(list_ar)

In [ ]:
sys.getsizeof(1) * len(list_ar)

112

In [ ]:
np_ar.itemsize * np_ar.size

32

# Numpy by:
> YT link: 