# NumPy  

## by Code with Harry
>YouTube video link: https://www.youtube.com/watch?v=Rbh1rieb3zc

### Why Numpy?
* Numpy provides efficient storage
  * uses relatively less memory to store data
* It's fast
* Unlike lists **randomly accessible**  


In [1]:
import numpy as np

In [ ]:
myarr = np.array([[3,6,3266646, 7]], np.int32)

In [ ]:
myarr[0,1]

6

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr.dtype

dtype('int32')

In [ ]:
myarr

array([[      3,       6, 3266646,       7]], dtype=int32)

### Array creation: Conversion from other Python structures

In [ ]:
listarray = np.array([[1,2,3], [5,8,5], [8,0,3]])

In [ ]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [8, 0, 3]])

In [ ]:

listarray.dtype

dtype('int64')

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.size

9

In [ ]:
np.array({34,21,23})
# objects not efficient for calculations

array({34, 21, 23}, dtype=object)

In [ ]:
# 
zeros = np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

dtype('float64')

In [ ]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace = np.linspace(0,36,5)
lspace

array([ 0.,  9., 18., 27., 36.])

In [ ]:
emp = np.empty((4,3))
emp

array([[4.68298782e-310, 4.68298760e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.36598737e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
emp_like = np.empty_like(lspace)
emp_like

array([ 0.,  9., 18., 27., 36.])

In [ ]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr = arr.reshape(3, 33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(99,)

### NUMPY AXIS
> Number of axis required to represent the array

for a 2D array x is axis0 and y is axis1

In [ ]:
x = listarray

In [ ]:
x

array([[1, 2, 3],
       [5, 8, 5],
       [8, 0, 3]])

In [ ]:
x[0][0] =0

In [ ]:
x

array([[0, 2, 3],
       [5, 8, 5],
       [8, 0, 3]])

In [ ]:
listarray
# x points to listarray

array([[0, 2, 3],
       [5, 8, 5],
       [8, 0, 3]])

In [ ]:
x.sum(axis=0)

array([13, 10, 11])

In [ ]:
x.sum(axis=1)

array([ 5, 18, 11])

In [ ]:
x.T
# transpose

array([[0, 5, 8],
       [2, 8, 0],
       [3, 5, 3]])

In [ ]:
x.flat
# gives an iterator

In [ ]:
for item in x.flat:
  print(item)

0
2
3
5
8
5
8
0
3


In [ ]:
x.ndim
# number of dimension

2

In [ ]:
x.size
# no. of elements

9

In [ ]:
x.nbytes
# total bytes consumed

72

In [ ]:
one = np.array([1,3,51,43])

In [ ]:
one.argmax()
# index of max element

2

In [ ]:
one.argmin()

0

In [ ]:
one.argsort()
# indices in sorted array

array([0, 1, 3, 2])

In [ ]:
x.argmax()

4

In [ ]:
x.argsort()

array([[0, 1, 2],
       [0, 2, 1],
       [1, 2, 0]])

In [ ]:
x

array([[0, 2, 3],
       [5, 8, 5],
       [8, 0, 3]])

In [ ]:
x.argmax(axis=0)

array([2, 1, 1])

In [ ]:
x.argmax(axis=1)

array([2, 1, 0])

In [ ]:
y = x.T
y

array([[0, 5, 8],
       [2, 8, 0],
       [3, 5, 3]])

### Mathematical Operations

In [ ]:
x + y

array([[ 0,  7, 11],
       [ 7, 16,  5],
       [11,  5,  6]])

In [ ]:
x*y
# element wise multiplecation

array([[ 0, 10, 24],
       [10, 64,  0],
       [24,  0,  9]])

In [ ]:
np.sqrt(x)
# element wise sqrt

array([[0.        , 1.41421356, 1.73205081],
       [2.23606798, 2.82842712, 2.23606798],
       [2.82842712, 0.        , 1.73205081]])

In [ ]:
x.sum()

34

In [ ]:
x.max()

8

In [ ]:
np.where(x>5)

(array([1, 2]), array([1, 0]))

In [ ]:
type(np.where(x>5))

tuple

In [ ]:
np.count_nonzero(x)

7

In [ ]:
np.nonzero(x)

(array([0, 0, 1, 1, 1, 2, 2]), array([1, 2, 0, 1, 2, 0, 2]))

### Numpy storage comparision

In [ ]:
import sys

list_ar = [0,45, 5, 5]

In [ ]:
np_ar = np.array(list_ar)

In [ ]:
sys.getsizeof(1) * len(list_ar)

112

In [ ]:
np_ar.itemsize * np_ar.size

32

---


# Numpy IITM:
## Elementent wise multiplication
Element wise multiplication of two vectors is called the **Hadamard product**. The operator corresponding to it is $\odot$. For example, given two vectors:
$$
x = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}, y = \begin{bmatrix}
4\\
5\\
6
\end{bmatrix}
$$
we have:
$$
\boldsymbol{z} = \boldsymbol{x} \odot \boldsymbol{y}= \begin{bmatrix}
4\\
10\\
18
\end{bmatrix}
$$
In `NumPy` this is expressed as:

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = x * y
z

array([ 4, 10, 18])

## Scaling vectors

If $\boldsymbol{x}$ is a vector, scaling it by a constant $k$ is equivalent to element-wise multiplication by $k$. For example, given
$$
\boldsymbol{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
$$
we have:
$$
y = 3 \boldsymbol{x} = \begin{bmatrix}
3\\
6\\
9
\end{bmatrix}
$$
As you might have guessed by now, in `NumPy` this is as simple as:

In [5]:
x = np.array([1, 2, 3])
y = 3 * x
y

array([3, 6, 9])

Again note that this is different from what you would expect with a Python list. The `*` operator for lists would result in replication.

In [8]:
x = [1, 2, 3]
y = 6 * x
y

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

## Element-wise functions of vectors
Scaling a vector $\boldsymbol{x}$ by a constant $k$ can be seen as the output of the following function:
$$
f(\boldsymbol{x}) = \begin{bmatrix}
kx_1\\
\cdots\\
kx_m
\end{bmatrix}
$$
This is nothing but the function $f(x) = kx$ applied element-wise. `NumPy` extends this feature for any arbitrary function. For example, consider the function $g(x) = x^2$. This can be applied element-wise:
$$
g(\boldsymbol{x}) = \begin{bmatrix}
x_1^2\\
\cdots\\
x_m^2
\end{bmatrix}
$$
In `NumPy`, this translates to:

In [10]:
x = np.array([1, 2, 3, 4])
y = x ** 2
y

array([ 1,  4,  9, 16])

We can take up more complex functions as well. For example, let us take the case of `np.log10`, which is $\log_{10}$:

In [11]:
x = np.array([1, 10, 100, 1000, 10000, 100000])
y = np.log10(x)
y

array([0., 1., 2., 3., 4., 5.])

Usually, we will stick to the natural logarithm or $\log_e$. This is given by `np.log`.

In [12]:
x = np.array([1, np.e, np.e ** 2])
y = np.log(x)
y

array([0., 1., 2.])

## Dot Product
The dot product between two vectors $\mathbf{x}$ and $\mathbf{y}$ is given as follows:
$$
z = \mathbf{x} \cdot \mathbf{y} = \sum \limits_{j = 1}^{m} x_j y_j
$$
In `NumPy`, this could be done as follows:

In [13]:
x = np.array([1, 2, 3, 4])
y = np.array([-4, -5, -6, -7])

z = np.dot(x, y)
z

-60

## Vector of zeros or ones
On many occassions, we might want to create a `NumPy` array all of whose elements are zeros or ones or some other constant. If we want a vector of zeros, one way would be as follows:

In [15]:
x = np.array([0 for _ in range(4)])
x

array([0, 0, 0, 0])

Here, `NumPy` provides a method that makes our job even simpler:

In [16]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

For a vector of ones, we have

In [17]:
x = np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

## Transpose of a matrix
Given a matrix $\textbf{M}$:
$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$
then, its transpose $\textbf{M}^{T}$ is:
$$
\textbf{M}^{T} = \begin{bmatrix}
1 & 4\\
2 & 5\\
3 & 6
\end{bmatrix}
$$
In `NumPy`, this becomes:

In [18]:
M = np.array([[1, 2, 3], [4, 5, 6]])
M_t = np.transpose(M)

M_t

array([[1, 4],
       [2, 5],
       [3, 6]])

Often, some methods in `NumPy` are also attributes of `NumPy` arrays. For example, this same operation of transposing a matrix can be done as follows:

In [19]:
M = np.array([[1, 2, 3], [4, 5, 6]])
M_t = M.T

M_t

array([[1, 4],
       [2, 5],
       [3, 6]])

You must be aware of both these ways of transposing a matrix.
## Product of two matrices
Given two matrices:
$$
\textbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
6 & 7\\
8 & 9\\
10 & 11
\end{bmatrix}
$$
then,
$$
\textbf{C} = \textbf{A} \times \textbf{B} = \begin{bmatrix}
52 & 58\\
124 & 139
\end{bmatrix}
$$
In `NumPy`, this becomes:

In [20]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 7], [8, 9], [10, 11]])

C = A @ B
C

array([[ 52,  58],
       [124, 139]])

## Matrix of zeros
In many algorithms, we might have to initialize a matrix with zeros. For example, consider a $2 \times 4$ matrix:
$$
\mathbf{M} = \begin{bmatrix}
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{bmatrix}
$$
In `NumPy` this can be done as follows:

In [21]:
M = np.zeros((2, 4))
M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Note that the shape of the matrix is $(2, 4)$. Consequently, the argument to the method `np.zeros` should be a tuple if you want to create a matrix of zeros. Specifying it as `np.zeros(2, 4)` will throw an error!

## Identity matrix
Often, we might have to deal with identity matrices. A $3 \times 3$ identity matrix is as follows:
$$
\mathbf{I} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}
$$
In `NumPy` this becomes:

In [22]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Reshaping
We can reshape a matrix into another matrix as well. Sometimes, we may not want to specify the dimensions completely. In such cases, we can let `NumPy` figure it out. For example
$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$
Let us say we want to reshape it in such a way that there are three rows:
$$
\mathbf{P} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}
$$

In [23]:
M = np.array([[1, 2, 3], [4, 5, 6]])
P = M.reshape((3, -1))
P

array([[1, 2],
       [3, 4],
       [5, 6]])

$-1$ refers to the unknown dimension, which we let `NumPy` compute.

## Matrix-vector addition (broadcasting)
In many ML models, we would have to add a vector to each row or column of a matrix. For example, consider the following case for row-wise addition:
### Row-wise addition
$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}, \mathbf{b} = \begin{bmatrix}
1 & 1 & 1 & 1
\end{bmatrix}
$$
This is slight abuse of notation as we can't add a matrix and a vector together. However, the context often makes this clear:
$$
\mathbf{M} + \mathbf{b} = \begin{bmatrix}
2 & 3 & 4 & 5\\
6 & 7 & 8 & 9
\end{bmatrix}
$$
In `NumPy` this becomes:

In [24]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 1, 1, 1])
print('Shape of M:', M.shape)
print('Shape of b:', b.shape)

M + b

Shape of M: (2, 4)
Shape of b: (4,)


array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

Notice how simple this is. Let us now do a slight variation. Let us say we wish to add a vector to each column of $\mathbf{M}$:
## Column-wise addition
$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}, \mathbf{b} = \begin{bmatrix}
1\\
2
\end{bmatrix}
$$
In the case, we have:
$$
\mathbf{M} + \mathbf{b} = \begin{bmatrix}
2 & 3 & 4 & 5\\
7 & 8 & 9 & 10
\end{bmatrix}
$$
Let us see if the same syntax works:

In [25]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 2])
print('Shape of M:', M.shape)
print('Shape of b:', b.shape)

### Caution! ###
# You can uncomment the next line and see what happens
# M + b
### Caution! ###

Shape of M: (2, 4)
Shape of b: (2,)


If you uncomment it and run it, you get a ValueError. Notice that the same syntax doesn't work. The error is suggestive:  
> operands could not be broadcast together with shapes `(2, 4)` and `(2, )`  

We will first discuss a way to fix this and then move onto why this behaviour is observed.  

In [26]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 2])
print('Shape of M:', M.shape)
print('Shape of b before adding dimension:', b.shape)
b = np.expand_dims(b, 1)
print('Shape of b after adding dimension:', b.shape)

M + b

Shape of M: (2, 4)
Shape of b before adding dimension: (2,)
Shape of b after adding dimension: (2, 1)


array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

`np.expand_dims` expands the dimension of a `NumPy` array. The first argument is the array and the second argument is the axis along which the array has to be expanded. Here, we want to treat `b` as a column vector. This is nothing but a `(2, 1)` matrix. So, the second argument is 1 (zero-indexing).

But why is this necessary? For adding a row vector to a matrix, we just had to use `M + b`. For adding a column vector to a matrix, we had to add an extra dimension to `b` and then add it to `M`. The answer to this lies with something called broadcasting.

### Broadcasting
When two arrays of different dimensions are combined together using an arithmetic operation such as `+`, `NumPy` sees if it can **broadcast** them. This is best understood with images. Here is an example from the `NumPy` docs on row-wise addition:

![](https://numpy.org/doc/stable/_images/broadcasting_2.png)

**Source**: https://numpy.org/doc/stable/user/basics.broadcasting.html

For column-wise addition, simple addition doesn't work:

![](https://numpy.org/doc/stable/_images/broadcasting_3.png)

**Source**: https://numpy.org/doc/stable/user/basics.broadcasting.html

In this course, we will mainly stick to matrix-vector addition or multiplication. This is the recipe:

- Row-wise
  - `M + b`
- Column-wise: 
  - Make `b` a column vector or a `(m, 1)` matrix using `np.expand_dims`
  - `M + b`

## Indexing and Slicing an array
Just like lists in Python, `NumPy` arrays can be indexed and sliced. Slicing is useful if we want to work with a portion of an array. For example, consider the matrix $\mathbf{M}$:
$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8\\
9 & 10
\end{bmatrix}
$$
The third row of this matrix is `M[2]`. This is just basic indexing.

In [28]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[2]

array([5, 6])

This behaviour is similar to what happens with Python lists. Let us say that we wish to extract the second column of this matrix. How would we do this?

In [29]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[:, 1]

array([ 2,  4,  6,  8, 10])

An $n$-dimensional array has $n$ axes. In the case of a matrix, a $2$D array, the first axis (index 0) refers to the rows and the second axis (index 1) refers to the columns.

In the example given above, `M[:, 1]`, the second axis is fixed as 1 while the first axis is fluid. In more concrete terms, we have selected the second column. Had we wanted a particular element, say the first element, from the second column, we would have used the notation `M[0, 1]`. But, since we want all the elements from the second column, we use the `:` operator without specifiying the start and end indices. Recall that this behaviour is similar to Python lists. If `L` is a list, then `L[:]` represents the completel list.

Now, consider the same matrix $\mathbf{M}$. We want to extract the third and fourth rows of this matrix. How do we do that?

In [30]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[2: 4]

array([[5, 6],
       [7, 8]])

This is again similar to the Python slicing notation. Now, if we wanted the second and third elements in the first column of the matrix, this is what we would do:

In [31]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[1: 3, 0]

array([3, 5])

## Stacking arrays
Sometimes, we would want to stack arrays. Consider the two matrices:
$$
\mathbf{A} =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\mathbf{B} =
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$
There are two ways to stack these two matrices:

### Row-wise
We could stack the two matrices along the rows, $\mathbf{A}$ on top of $\mathbf{B}$:
$$
\mathbf{C} =
\begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8
\end{bmatrix}
$$
This would be done as follows:

In [32]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.concatenate((A, B), axis = 0)
print(C.shape)
print(C)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Column-wise
We could stack the two matrices along the columns, $\mathbf{A}$ to the left of $\mathbf{B}$:
$$
\mathbf{C} =
\begin{bmatrix}
1 & 2 & 5 & 6\\
3 & 4 & 7 & 8\\
\end{bmatrix}
$$
This would be done as follows:

In [33]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.concatenate((A, B), axis = 1)
print(C.shape)
print(C)

(2, 4)
[[1 2 5 6]
 [3 4 7 8]]


## Sum, Mean and Variance
Sometimes we may wish to compute the sum of a particular slice of an array. For example, consider the matrix:
$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}
$$
The sum of the rows of the matrix is a vector:
$$
\text{rsum}(\mathbf{A}) = \begin{bmatrix}
10\\
26
\end{bmatrix}
$$
In `NumPy` this can be done as follows:

In [34]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
rsum = np.sum(A, axis = 1)
rsum

array([10, 26])

We have added the elements of the array along the axis $1$. This has the same effect as summing the rows of the array. Now, we shall move to the column sum:
$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8
\end{bmatrix}
$$
The sum of the columns of the matrix is a vector:
$$
\text{csum}(\mathbf{A}) = \begin{bmatrix}
6\\
8\\
10\\
12
\end{bmatrix}
$$

In [35]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
csum = np.sum(A, axis = 0)
csum

array([ 6,  8, 10, 12])

It is important to note that `sum` is an attribute of `NumPy` arrays. So we can also express this as:

In [36]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
rsum = A.sum(axis = 1)
csum = A.sum(axis = 0)

print('Sum of the rows:', rsum)
print('Sum of the columns:', csum)

Sum of the rows: [10 26]
Sum of the columns: [ 6  8 10 12]


Just like `sum`, we have `mean` to find out the mean of parts of an array.